sudo: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack:
    rooms:
      - rhway:VfKOy61tSbzZwZXAe8KnPnNj#homepage-redesign
node_js:
  - 'stable'
install:
  - npm install
addons:
  apt:
    packages:
      - s3cmd
script:
  - make build
  - npm run lint
after_success:
  - make deploy
