sudo: false
language: node_js
cache:
  directories:
  - "~/.yarn"
  - "~/.nvm"
notifications:
  email: false
  slack:
    rooms:
      secure: QAYTd9rDT12gNX5Q0GXCQLcHadgxsj9tfs36qLGE1juj0CxRZVZLDKs/QB3Ri8LnhyGz/SlQU62f9kdjbyg8dIps708ezzQV06KQs3qHintEFMGr+Fm/twcYTgB3FXaYHvxZQ+3dNLt+FDKwFCC7tjXK9Dl5xYWlk8EgNtgr/BKLDe1QratjKqZtKiXEPjByLH15stslFDLP65mP2QDPYvIj5+d3tY0tLCY0y0dCuRUrwB+EvpklPlbVDqgnXHbdIlBSbIEodMT7V+zqvhnlyxzLBGNEHnoGLxDcDah4jByhf4MIE1MRrZQdptgLFHpeVtl1xoyCtqip/1fk9ZSTEoMEsINa7TeTJdgP1O0q+2HRadspEw/5z62PpjnQjAcpStD/aMTeKogt9XTRq8BVfl5dkAwJkOH6ItGSILLmmFxfkhTfaoluUrIVGGFJ7Sb3wfgYJkE8L/bnKDZfONyaAN7aisXohenrmsGvmFJhXpzhA+pjdZ/IwN1ohsVGCo6FOZcYj1rR/Sdw+oCgVNUdlK+pZev3Wd5DOCXW5zzIEmNE91MRTNp3r80xvejq5jU10Z4CQT7Ah7kug3U5+x4c8PwCPihPjUjfBQjOUe9Yl7ASMkalAJsvEl68i5CDdqEuutUEBmEMvQpOvrJcGFWBnds8xJBMtkGtqKVJc15Blls=
node_js:
- stable
before_install:
- pip install --user s3cmd
- npm install -g yarn
install:
- yarn
addons:
  apt:
    packages:
    - python-pip
script:
- npm run lint
- |
  if [ -n "${TRAVIS_TAG}" ]; then
    APP=RH AWS__WEBSITE_BUCKET=2016.resourceful-humans.com make deploy
    APP=netwoRHk AWS__WEBSITE_BUCKET=networhk.net make deploy
  fi
- |
  if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
    APP=RH AWS__WEBSITE_BUCKET=2016.resourceful-humans.com make preview
    APP=netwoRHk AWS__WEBSITE_BUCKET=networhk.net make preview
  fi
