sudo: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack:
    rooms:
      - rhway:VfKOy61tSbzZwZXAe8KnPnNj#homepage-redesign
node_js:
  - 'stable'
install:
  - pip install --user s3cmd
  - npm install
addons:
  apt:
    packages:
      - python-pip
script:
  - make build
  - npm run lint
after_success:
  - echo "[default]" > /home/travis/.s3cfg
  - echo "access_key = " >> /home/travis/.s3cfg
  - echo "secret_key = " >> /home/travis/.s3cfg
  - PATH=$PATH:$HOME/.local/bin make deploy
