sudo: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack:
    rooms:
      - rhway:$SLACK__TOKEN#$SLACK__CHANNEL
node_js:
  - 'stable'
install:
  - npm install
addons:
  apt:
    packages:
      - s3cmd
script:
  - make build
  - npm run lint
after_success:
  - rm build/js/index.js
  - rm build/css/index.css
  - s3cmd sync --access_key=$AWS__ACCESS_KEY --secret_key=$AWS__SECRET_KEY --delete-removed ./build/ s3://$AWS__WEBSITE_BUCKET/
