sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack:
    rooms:
      - rhway:VfKOy61tSbzZwZXAe8KnPnNj#z_tech_github
services:
  - redis-server
node_js:
  - 'stable'
script:
  - make build
  - npm run lint
  - npm run test:coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
