sudo: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack:
    rooms:
      - rhway:VfKOy61tSbzZwZXAe8KnPnNj#z_tech_github
node_js:
  - 'stable'
install:
  - pip install --user s3cmd
  - npm install
addons:
  apt:
    packages:
      - python-pip
script:
  - npm run lint
  - make deploy
